### ISSUE TITLE
Question regarding parameter output

### ISSUE THREAD

**Issue by tsveth** [saezlab/CNORode#4]
Hi fellow CNORode users,
Using CNORode I get some nice graphs following the following code:

> opt_pars=parEstimationLBode(cnolist,model, method="essm", ode_parameters=ode_parameters, paramsSSm=paramsSSm)
> simulatedData=plotLBodeFitness(cnolist, model, transfer_function=transferFun, ode_parameters=opt_pars, reltol = 1e-6, atol = 1e-6, maxStepSize = 1)

The graph looks nice! However, I can't find where the transfer functions are stored. e.g. where can I find the tau, k, and n values to evaluate the effect from one node to the next?

Thanks for all the help!

**Comment by gabora** [comment]
Hi @tsveth, 
sorry for the delayed reaction, did you figure it out or is it still a question? 
best,
Attila

**Comment by tsveth** [comment]
Hi gabora,
Thank you for the reply! Fortunately I found the values.
Best
T
